2025-09-17 12:28:51,618 - INFO - Запуск обучения модели
2025-09-17 12:28:51,879 - INFO - Загружено 284807 строк из data/data_alter.csv
2025-09-17 12:28:51,888 - INFO - Удалены колонки: ['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28']
2025-09-17 12:28:51,915 - INFO - Балансировка: 492 положительных, 50000 отрицательных
2025-09-17 12:28:57,379 - INFO - Модель обучена
2025-09-17 12:28:57,400 - INFO - Метрики: {'roc_auc': 0.8065530181675711, 'accuracy': 0.9905931280324785, 'precision': 0.5789473684210527, 'recall': 0.11224489795918367, 'f1': 0.18803418803418803}
2025-09-17 12:28:57,413 - INFO - Старая модель перемещена в models/archive
2025-09-17 12:28:57,446 - INFO - Новая модель сохранена в models/latest/2025-09-17_12-28.cbm
2025-09-17 12:29:22,573 - INFO - Запуск обучения модели
2025-09-17 12:29:22,819 - INFO - Загружено 284807 строк из data/data_alter.csv
2025-09-17 12:29:22,827 - INFO - Удалены колонки: ['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28']
2025-09-17 12:29:22,870 - INFO - Балансировка: 492 положительных, 50000 отрицательных
2025-09-17 12:29:33,714 - INFO - Модель обучена
2025-09-17 12:29:33,767 - INFO - Метрики: {'roc_auc': 0.8065530181675711, 'accuracy': 0.9905931280324785, 'precision': 0.5789473684210527, 'recall': 0.11224489795918367, 'f1': 0.18803418803418803}
2025-09-17 12:29:33,810 - INFO - Старая модель перемещена в models/archive
2025-09-17 12:29:33,856 - INFO - Новая модель сохранена в models/latest/2025-09-17_12-29.cbm
2025-09-18 02:43:14,724 - INFO - Запуск обучения модели
2025-09-18 02:43:14,812 - INFO - Загружено 284807 строк из data/data_alter.csv
2025-09-18 02:43:14,818 - INFO - Удалены колонки: ['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28']
2025-09-18 02:43:14,840 - INFO - Балансировка: 492 положительных, 50000 отрицательных
2025-09-18 02:43:19,836 - INFO - Модель обучена
2025-09-18 02:43:19,851 - INFO - Метрики: {'roc_auc': 0.8065530181675711, 'accuracy': 0.9905931280324785, 'precision': 0.5789473684210527, 'recall': 0.11224489795918367, 'f1': 0.18803418803418803}
2025-09-18 02:43:19,909 - INFO - Новая модель сохранена в models/latest/2025-09-18_02-43.cbm
2025-09-18 02:56:36,086 - INFO - Запуск обучения модели
2025-09-18 02:56:36,185 - INFO - Загружено 284807 строк из data/data_alter.csv
2025-09-18 02:56:36,192 - INFO - Удалены колонки: ['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28']
2025-09-18 02:56:36,216 - INFO - Балансировка: 492 положительных, 50000 отрицательных
2025-09-18 02:56:41,172 - INFO - Модель обучена
2025-09-18 02:56:41,188 - INFO - Метрики: {'roc_auc': 0.8065530181675711, 'accuracy': 0.9905931280324785, 'precision': 0.5789473684210527, 'recall': 0.11224489795918367, 'f1': 0.18803418803418803}
2025-09-18 02:56:41,200 - INFO - Старая модель перемещена в models/archive
2025-09-18 02:56:41,249 - INFO - Новая модель сохранена в models/latest/2025-09-18_02-56.cbm
2025-09-18 02:59:50,634 - INFO - Запуск обучения модели
2025-09-18 02:59:50,709 - INFO - Загружено 284807 строк из data/data_alter.csv
2025-09-18 02:59:50,715 - INFO - Удалены колонки: ['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28']
2025-09-18 02:59:50,735 - INFO - Балансировка: 492 положительных, 50000 отрицательных
2025-09-18 02:59:54,535 - INFO - Модель обучена
2025-09-18 02:59:54,555 - INFO - Метрики: {'roc_auc': 0.8065530181675711, 'accuracy': 0.9905931280324785, 'precision': 0.5789473684210527, 'recall': 0.11224489795918367, 'f1': 0.18803418803418803}
2025-09-18 02:59:54,568 - INFO - Старая модель перемещена в models/archive
2025-09-18 02:59:54,628 - INFO - Новая модель сохранена в models/latest/2025-09-18_02-59.cbm
2025-09-18 03:01:09,314 - INFO - Запуск обучения модели
2025-09-18 03:01:09,411 - INFO - Загружено 284807 строк из data/data_alter.csv
2025-09-18 03:01:09,418 - INFO - Удалены колонки: ['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28']
2025-09-18 03:01:09,443 - INFO - Балансировка: 492 положительных, 50000 отрицательных
2025-09-18 03:01:14,487 - INFO - Модель обучена
2025-09-18 03:01:14,505 - INFO - Метрики: {'roc_auc': 0.8065530181675711, 'accuracy': 0.9905931280324785, 'precision': 0.5789473684210527, 'recall': 0.11224489795918367, 'f1': 0.18803418803418803}
2025-09-18 03:01:14,518 - INFO - Старая модель перемещена в models/archive
2025-09-18 03:01:14,595 - INFO - Новая модель сохранена в models/latest/2025-09-18_03-01.cbm
2025-09-18 12:45:32,898 - INFO - Запуск обучения модели
2025-09-18 12:45:32,999 - INFO - Загружено 284807 строк из /app/data/data_alter.csv
2025-09-18 12:45:33,006 - INFO - Удалены колонки: ['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28']
2025-09-18 12:45:33,031 - INFO - Балансировка: 492 положительных, 50000 отрицательных
2025-09-18 12:45:36,943 - INFO - Модель обучена
2025-09-18 12:45:36,959 - INFO - Метрики: {'roc_auc': 0.8065530181675711, 'accuracy': 0.9905931280324785, 'precision': 0.5789473684210527, 'recall': 0.11224489795918367, 'f1': 0.18803418803418803}
2025-09-18 12:45:36,971 - INFO - Старая модель перемещена в /app/models/archive
2025-09-18 12:45:37,023 - INFO - Новая модель сохранена в /app/models/latest/2025-09-18_12-45.cbm
2025-09-18 12:45:37,042 - INFO - Модель успешно обновлена в inference сервисе
2025-09-20 02:28:01,801 - INFO - Запуск обучения модели
2025-09-20 02:28:01,893 - INFO - Загружено 284807 строк из /app/data/data_alter.csv
2025-09-20 02:28:01,898 - INFO - Удалены колонки: ['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28']
2025-09-20 02:28:01,919 - INFO - Балансировка: 492 положительных, 50000 отрицательных
2025-09-20 02:28:06,745 - INFO - Модель обучена
2025-09-20 02:28:06,759 - INFO - Метрики: {'roc_auc': 0.8065530181675711, 'accuracy': 0.9905931280324785, 'precision': 0.5789473684210527, 'recall': 0.11224489795918367, 'f1': 0.18803418803418803}
2025-09-20 02:28:06,773 - INFO - Старая модель перемещена в /app/models/archive
2025-09-20 02:28:06,849 - INFO - Новая модель сохранена в /app/models/latest/2025-09-20_02-28.cbm
2025-09-20 02:28:10,794 - ERROR - Ошибка при запросе к inference сервису
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 493, in _make_request
    conn.request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 494, in request
    self.endheaders()
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 325, in connect
    self.sock = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPConnection object at 0x7bed0b2accd0>: Failed to resolve 'ml_inference' ([Errno -2] Name or service not known)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 644, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='ml_inference', port=8000): Max retries exceeded with url: /load_model (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7bed0b2accd0>: Failed to resolve 'ml_inference' ([Errno -2] Name or service not known)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/train.py", line 118, in main
    response = requests.post(url, json=payload)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 677, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ml_inference', port=8000): Max retries exceeded with url: /load_model (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7bed0b2accd0>: Failed to resolve 'ml_inference' ([Errno -2] Name or service not known)"))
